### PR TITLE
Code reformat

### PR DESCRIPTION
**Pull request by GCHQDeveloper42**
Improvements to code readability, format & Javadocs.

Summary of Changes: 
- Improved Javadoc descriptions.
- Set max line length & comment length to 120 characters in checkstyle rules.
- Moved HqdmObject from model.impl to pojo package.
- Moved HqdmException class from RDF module to core.
- Moved Pair & Triples classes to util package in hqdm-rdf.
- Replaced StringBuilder with string concatenation in Triples class for readability.
- Descriptive test names and variables.

### CODE REVIEW

**Comment by twalmsley** [comment]
- There are now two copies of `HqdmObject` - one in `model` and one in `pojo`.
- Both are exposed to clients of the module, but it is an internal implementation class and should not be exposed.
- `HqdmException` is in the `exception` package not in the `core` package (PR description says it has moved to `core`)
- Can you add your code formatter config to the repo so that contributors can use it? (possibly also for the `MagmaCore` repo as well)

**Comment by GCHQDeveloper42** [comment]
- I intended to move HqdmObject to the `pojo` package, not copy it. I will remove whichever copy we agree not to use.
  - I'd prefer to keep HqdmObject in the `pojo` package as this makes it distinct from the HQDM model interfaces and makes it easier to find in the source.
- Does Top.java need to be exposed to the client? If not then we can remove `uk.gov.gchq.hqdm.core.pojo` from the module exports, thereby hiding both HqdmObject and Top.
- The Java formatter settings I'm using are included in the `.vscode` folder which is excluded by the .gitignore file. What would be the best way for me to include it in the project source? I'm using the same formatter for Magma Core so I will include there as well.

**Comment by twalmsley** [comment]
- I tried not exporting the `pojo` package and my local MC builds and tests ok, so it looks like it can be excluded from the `exports`, which also means that the `pojo` package will be fine for `HqdmObject`.
- I'd include a copy of the formatter config file at the root with maybe a comment in the `CONTRIBUTING.md` file about using it for formatting - you could say copy it to your local `.vscode` directory for VS Code users, and leave it up to people to configure it for their preferred IDE.

**Comment by twalmsley** [comment]
Looks good to me - feel free to merge it 👍 .

I can also update MC to use this version unless you want to do it? (this should be done before the MC modularisation changes)

**Comment by GCHQDeveloper42** [comment]
I'll do this. I want to make the same formatting changes to Magma Core before both updating the dependency version and modularising Magma Core.

**Pull request merged**
